CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username TEXT UNIQUE,
  email TEXT UNIQUE,
  password TEXT,
  google_id TEXT UNIQUE,
  auth_provider TEXT NOT NULL DEFAULT 'local'
);


CREATE TABLE blogs (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);

ALTER TABLE users
ADD COLUMN name TEXT,
ADD COLUMN bio TEXT,
ADD COLUMN profile_picture TEXT,
ADD COLUMN website TEXT,
ADD COLUMN location TEXT

ALTER TABLE blogs
ADD COLUMN published BOOLEAN DEFAULT FALSE;